# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: df725cfcfd0122c22dc71926fe1990157d3ef804e322f5244fc0fe0c8514a3908df246e21395abad9dcd2dce83e1875167cce834c50fb3e56d17b344992c10c3

test:
  secret_key_base: f63dcf215259f316618ac3cc5016f8e24cab1c990a8bdd72458bd3444036009164154ff1d42c79f8ce59f011a8c3227ca77fc44093c14cfbbcfc8e5ef4f58adf

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
